import { type TSchema, Type } from "@sinclair/typebox";
import * as Entities from "./entities.js";
import * as Metrics from "./metrics.js";
import * as Ops from "./operations.js";
import * as Plans from "./plans.js";
import * as P from "./primitives.js";
import * as Protocol from "./protocol.js";
import { ErrorEnvelope, mcpTools, SuccessEnvelope } from "./surfaces.js";

const names = Type.Array(P.Name);
/** Model-facing citation of supplied evidence (`E1`, `E2`, …); resolved by the application. */
const EvidenceHandle = Type.String({ pattern: "^E[1-9][0-9]{0,5}$" });
const evidenceIds = (minItems: number) => Type.Array(EvidenceHandle, { minItems, maxItems: 100 });
const supplemental = {
  DocumentValidationInput: P.Obj({
    schema: P.Enum(["ExecutablePlan", "ProjectConfig", "RunRequest"]),
    document: P.Json,
  }),
  DocumentValidationResult: P.Obj({ validated: Type.Literal(true), schema: P.Name }),
  AIRequirementsOutput: P.Obj({
    requirements: Type.Array(
      P.Obj({
        key: P.Name,
        text: P.Description,
        acceptanceCriteria: Type.Array(P.Description, { minItems: 1 }),
        evidenceIds: evidenceIds(1),
        originKind: P.Enum(["explicit", "user_spec", "inferred", "observed"]),
        confidence: Type.Union([Type.Number({ minimum: 0, maximum: 1 }), Type.Null()]),
        reason: P.Description,
      }),
      { minItems: 1, maxItems: 100 },
    ),
    conflicts: Type.Array(
      P.Obj({
        keys: Type.Array(P.Name, { minItems: 2 }),
        reason: P.Description,
        evidenceIds: evidenceIds(2),
      }),
    ),
    openQuestions: Type.Array(P.Description),
  }),
  AIRequirementConflictsOutput: P.Obj({
    conflicts: Type.Array(
      P.Obj({
        keys: Type.Array(P.Name, { minItems: 2 }),
        reason: P.Description,
        evidenceIds: evidenceIds(2),
      }),
    ),
    openQuestions: Type.Array(P.Description),
  }),
  AIProposalsOutput: P.Obj({
    proposals: Type.Array(
      P.Obj({
        plan: Plans.ExecutablePlan,
        requirementRefs: Type.Array(P.id("req"), { minItems: 1 }),
        evidenceIds: evidenceIds(1),
        warnings: names,
      }),
      { minItems: 1, maxItems: 50 },
    ),
  }),
  Empty: P.Obj({}),
  TokenBudgetInput: P.Obj({ tokens: P.Nonnegative }),
  Binary: Type.String({ contentEncoding: "base64" }),
  Health: P.Obj({ status: P.Enum(["alive", "ready", "unavailable"]) }),
  ProjectInput: P.Obj({
    name: P.Name,
    workspaceId: Type.Optional(P.id("ws")),
    defaultEnvironmentId: Type.Optional(P.id("env")),
  }),
  WorkspaceInput: P.Obj({
    name: Type.Optional(P.Name),
    settingsVersion: Type.Optional(P.Version),
    quotaPolicyId: Type.Optional(P.Name),
  }),
  MembershipInput: P.Obj({
    principalId: P.EntityId,
    role: P.Enum(P.roles),
    projectRestrictions: Type.Array(P.id("prj")),
  }),
  TokenInput: P.Obj({ name: P.Name, scopes: names, expiresAt: P.Timestamp }),
  TokenMetadata: P.Obj({ id: P.Name, name: P.Name, scopes: names, expiresAt: P.Timestamp }),
  EnvironmentInput: P.Obj({
    name: P.Name,
    baseUrl: Type.String({ format: "uri" }),
    networkProfile: P.Enum(["public", "private", "local-loopback"]),
    authRefs: Type.Optional(Type.Array(P.id("aup"))),
    production: Type.Optional(Type.Boolean()),
  }),
  DefaultEnvironmentInput: P.Obj({ environmentId: P.id("env") }),
  SecretInput: P.Obj({
    name: P.Name,
    value: Type.Optional(Type.String()),
    secretRef: Type.Optional(P.id("sec")),
    allowedOrigins: names,
  }),
  ConfirmationInput: P.Obj({ confirmationToken: P.Name }),
  UploadReceipt: P.Obj({
    uploadId: P.Name,
    contentHash: P.ContentDigest,
    sizeBytes: P.Nonnegative,
    state: P.Enum(["pending", "complete"]),
    target: Type.Optional(Type.String()),
    token: Type.Optional(Type.String()),
  }),
  SourceInput: P.Obj({
    role: P.Name,
    name: P.Name,
    uploadId: P.Name,
    sourceId: Type.Optional(P.id("src")),
  }),
  DiscoveryRetryInput: P.Obj({
    featureIds: Type.Array(P.id("fea")),
    inputsFingerprint: Type.Optional(P.ContentDigest),
  }),
  RequirementsInput: P.Obj({ requirements: Type.Array(Entities.entities.Requirement) }),
  GenerationInput: P.Obj({ inputRefs: Type.Array(P.EvidenceRef), scope: names, budget: P.Json }),
  ProposalDecisionInput: P.Obj({
    proposalIds: Type.Array(P.id("pro")),
    expectedVersion: P.Version,
    reason: Type.Optional(P.Description),
  }),
  ProposalDecisionReceipt: P.Obj({
    accepted: Type.Array(P.id("tst")),
    retained: Type.Array(P.id("pro")),
    rejected: Type.Array(P.id("pro")),
  }),
  TestMetadataInput: P.Obj({
    name: Type.Optional(P.Name),
    tags: Type.Optional(names),
    priority: Type.Optional(P.Priority),
  }),
  PromoteInput: P.Obj({
    revisionId: P.id("rev"),
    expectedActiveRevisionId: P.id("rev"),
    approval: Type.Optional(P.id("apr")),
  }),
  CancelInput: P.Obj({ reason: Type.Optional(P.Description) }),
  RerunInput: P.Obj({ environmentId: Type.Optional(P.id("env")) }),
  BudgetInput: P.Obj({ budget: P.Json }),
  ExpectedVersionInput: P.Obj({ expectedVersion: P.Version }),
  RunComparisonRequest: P.Obj({ leftRunId: P.id("run"), rightRunId: P.id("run") }),
  BatchComparisonRequest: P.Obj({ leftBatchId: P.id("bat"), rightBatchId: P.id("bat") }),
  ComparisonResult: P.Obj({
    comparability: P.Enum(["comparable", "partially_comparable", "incomparable"]),
    reasons: names,
    differences: Type.Array(P.Obj({ field: P.Name, left: P.Json, right: P.Json })),
  }),
  FlakeStudyInput: P.Obj({
    testRevision: P.id("rev"),
    environment: P.id("env"),
    n: P.Positive,
    seed: Type.Integer(),
  }),
  BatchCancelReceipt: P.Obj({ batchId: P.id("bat"), members: Type.Array(Ops.CancelReceipt) }),
  CleanupInput: P.Obj({ approval: Type.Optional(P.id("apr")), ownerProof: P.EvidenceRef }),
  TunnelInput: P.Obj({
    binding: P.Name,
    ttlMs: P.Positive,
    host: P.Name,
    port: Type.Integer({ minimum: 1, maximum: 65535 }),
  }),
  TunnelMetadata: P.Obj({ id: P.Name, binding: P.Name, expiresAt: P.Timestamp }),
  HeartbeatInput: P.Obj({
    leaseId: P.id("job"),
    state: P.Enum(["ready", "draining", "offline"]),
    version: P.Version,
  }),
  IntegrationInput: P.Obj({
    provider: P.Name,
    destinationRef: P.Name,
    enabled: Type.Boolean(),
    settings: P.Json,
  }),
  IntegrationMetadata: P.Obj({
    id: P.Name,
    provider: P.Name,
    destinationRef: P.Name,
    enabled: Type.Boolean(),
  }),
  PortabilityInput: P.Obj({ package: P.Name, version: P.Name, options: P.Json }),
  OperationReceipt: P.Obj({
    jobId: P.id("job"),
    state: P.Enum(["queued", "running", "completed", "failed"]),
    progress: Type.Number({ minimum: 0, maximum: 1 }),
  }),
  IdentityInput: P.Obj({ principal: P.Name, credentialRef: Type.Optional(P.id("sec")) }),
  IdentityReceipt: P.Obj({
    principalId: P.EntityId,
    state: P.Enum(["authenticated", "revoked", "pending"]),
  }),
  SessionMetadata: P.Obj({ id: P.Name, principalId: P.EntityId, expiresAt: P.Timestamp }),
  AuthContinueInput: P.Obj({ inputRef: Type.Optional(P.id("sec")) }),
  AdmissionInput: P.Obj({ action: P.Enum(["pause", "resume"]), reason: P.Description }),
  ReconcileInput: P.Obj({
    mode: P.Enum(["preview", "apply"]),
    approval: Type.Optional(P.id("apr")),
  }),
  BackupInput: P.Obj({ destination: P.Name }),
  BootstrapReceipt: P.Obj({
    projectId: P.id("prj"),
    config: Ops.ProjectConfig,
    preflight: Type.Array(P.Obj({ check: P.Name, passed: Type.Boolean() })),
    nextActions: names,
  }),
  RequirementSnapshot: P.Obj({
    requirements: Type.Array(Entities.entities.Requirement),
    conflicts: Type.Array(P.Obj({ left: P.EvidenceRef, right: P.EvidenceRef })),
  }),
  GeneratedTestsReceipt: P.Obj({
    candidates: Type.Array(P.id("rev")),
    validationErrors: Type.Array(P.Obj({ path: P.Name, message: P.Description })),
  }),
  EvidenceSummary: P.Obj({
    manifest: Ops.ArtifactManifest,
    resources: Type.Array(Type.String({ minLength: 1, maxLength: 8192 })),
    integrity: P.Enum(["verified", "partial", "invalid"]),
    freshness: P.Enum(["current", "stale"]),
    verificationEligible: Type.Boolean(),
    nextCursor: Type.Union([Type.String(), Type.Null()]),
  }),
  ReportLocation: P.Obj({ location: Type.String() }),
};
const httpInputs = {
  ProjectPatchInput: Type.Partial(supplemental.ProjectInput),
  EnvironmentPatchInput: Type.Partial(supplemental.EnvironmentInput),
  ApprovalInput: P.Obj({
    actorId: Type.Optional(P.id("usr")),
    reviewerId: Type.Optional(P.id("usr")),
    actionSet: names,
    revisionHash: P.ContentDigest,
    environmentRevisionId: P.id("evr"),
    originSet: names,
    expiresAt: Type.Optional(P.Timestamp),
    policyHash: P.ContentDigest,
  }),
};
export const schemaCatalog: Readonly<Record<string, TSchema>> = Object.freeze({
  RatioMetric: Metrics.RatioMetric,
  CoverageMetrics: Metrics.CoverageMetrics,
  ExecutionMetrics: Metrics.ExecutionMetrics,
  RuntimeTiming: Metrics.RuntimeTiming,
  EntityId: P.EntityId,
  Timestamp: P.Timestamp,
  ContentDigest: P.ContentDigest,
  Money: P.Money,
  Version: P.Version,
  EvidenceRef: P.EvidenceRef,
  Pagination: P.Pagination,
  ExecutablePlan: Plans.ExecutablePlan,
  Step: Plans.Step,
  IntentPlan: Plans.IntentPlan,
  TestRevisionInput: Plans.TestRevisionInput,
  CodeReference: Plans.CodeReference,
  DependencyBinding: Plans.DependencyBinding,
  Locator: Plans.Locator,
  Value: P.Value,
  ProjectConfig: Ops.ProjectConfig,
  EffectiveConfig: Ops.EffectiveConfig,
  ExecutionLimits: Ops.ExecutionLimits,
  NetworkPolicy: Ops.NetworkPolicy,
  RunRequest: Ops.RunRequest,
  RunReceipt: Ops.RunReceipt,
  RunResult: Ops.RunResult,
  BatchRequest: Ops.BatchRequest,
  BatchReceipt: Ops.BatchReceipt,
  BatchResult: Ops.BatchReceipt,
  BundleMeta: Ops.BundleMeta,
  UploadRequest: Ops.UploadRequest,
  CancelReceipt: Ops.CancelReceipt,
  BackupManifest: Ops.BackupManifest,
  RestoreRequest: Ops.RestoreRequest,
  UsageEntry: Ops.UsageEntry,
  Event: Ops.Event,
  ...Entities.entities,
  FeatureMap: Entities.FeatureMap,
  DiscoveryRequest: Entities.DiscoveryRequest,
  DiscoveryResult: Entities.DiscoveryResult,
  ExecutionSnapshot: Entities.ExecutionSnapshot,
  IntegrationEvent: Entities.IntegrationEvent,
  CohortManifest: Entities.CohortManifest,
  EvaluationResult: Entities.EvaluationResult,
  TraceabilityRecord: Entities.TraceabilityRecord,
  ModelRequest: Entities.ModelRequest,
  ModelResponse: Entities.ModelResponse,
  RunnerEvent: Protocol.RunnerEvent,
  SupervisorEvent: Protocol.SupervisorEvent,
  AgentActionSelection: Protocol.AgentActionSelection,
  AIGeneratedCodeOutput: Protocol.AIGeneratedCodeOutput,
  CapabilityManifest: Protocol.CapabilityManifest,
  ErrorEnvelope,
  SuccessEnvelope: SuccessEnvelope(P.Json),
  ...supplemental,
  ...httpInputs,
  ...Object.fromEntries(
    Object.entries(mcpTools).map(([name, tool]) => [`Mcp_${name}`, tool.input]),
  ),
});
