import { type TSchema, Type } from "@sinclair/typebox";
import {
  ArtifactManifest,
  BatchCounts,
  ExecutionLimits,
  PermissionGrant,
  RunResult,
  StepResult,
  VariableCapture,
} from "./operations.js";
import { CodeReference, ExecutablePlan, IntentPlan } from "./plans.js";
import {
  AnalysisStatus,
  ArtifactState,
  CleanupOutcome,
  ContentDigest,
  Description,
  type EntityPrefix,
  Enum,
  EvidenceRef,
  Gate,
  id,
  Json,
  Mode,
  Name,
  Nonnegative,
  Obj,
  Outcome,
  Phase,
  Priority,
  RedactionStatus,
  roles,
  Timestamp,
  Version,
} from "./primitives.js";
import { reasonCodes } from "./registries.js";

const nullable = <T extends TSchema>(schema: T) => Type.Union([schema, Type.Null()]);
const refs = Type.Array(EvidenceRef);
const names = Type.Array(Name);
const digest = nullable(ContentDigest);
const entity = <F extends Record<string, TSchema>>(prefix: EntityPrefix, fields: F) =>
  Obj({
    id: id(prefix),
    workspaceId: Type.Optional(id("ws")),
    createdAt: Type.Optional(Timestamp),
    version: Type.Optional(Version),
    ...fields,
    extensions: Type.Optional(
      Type.Record(Type.String({ pattern: "^[a-z][a-z0-9-]*:[A-Za-z0-9_-]+$" }), Json),
    ),
  });
export const entities = {
  Workspace: entity("ws", {
    name: Name,
    mode: Enum(["single-user", "server", "distributed"]),
    settingsVersion: Version,
    quotaPolicyId: Name,
  }),
  Principal: Type.Union([
    entity("usr", {
      kind: Type.Literal("human"),
      displayName: Name,
      disabledAt: nullable(Timestamp),
    }),
    entity("svc", {
      kind: Type.Literal("service"),
      displayName: Name,
      disabledAt: nullable(Timestamp),
    }),
  ]),
  Membership: entity("mem", {
    workspaceId: id("ws"),
    principalId: Type.Union([id("usr"), id("svc")]),
    role: Enum(roles),
    projectRestrictions: Type.Array(id("prj")),
  }),
  Project: entity("prj", {
    workspaceId: id("ws"),
    name: Name,
    slug: Name,
    defaultEnvironmentId: nullable(id("env")),
    archivedAt: nullable(Timestamp),
  }),
  Environment: entity("env", {
    projectId: id("prj"),
    name: Name,
    activeRevisionId: id("evr"),
    archivedAt: nullable(Timestamp),
  }),
  EnvironmentRevision: entity("evr", {
    targetOrigins: names,
    networkProfile: Enum(["public", "private", "local-loopback"]),
    authProfileRefs: Type.Array(id("aup")),
    locale: Name,
    timezone: Name,
    variables: Type.Record(Type.String(), VariableCapture),
    production: Type.Boolean(),
  }),
  SecretReference: entity("sec", {
    workspaceId: id("ws"),
    provider: Name,
    locator: Name,
    secretVersion: Version,
    allowedOrigins: names,
    revokedAt: Type.Optional(nullable(Timestamp)),
  }),
  Source: entity("src", {
    projectId: id("prj"),
    role: Name,
    displayName: Name,
    origin: Name,
    activeRevisionId: nullable(id("svr")),
  }),
  SourceRevision: entity("svr", {
    contentHash: ContentDigest,
    mediaType: Name,
    sizeBytes: Nonnegative,
    parserVersion: Name,
    status: Enum(["ready", "partial", "needs_input", "invalid"]),
    parentId: nullable(id("svr")),
    chunks: Type.Optional(refs),
  }),
  CodeSnapshot: entity("csp", {
    repoRef: Name,
    baseSha: nullable(Name),
    headSha: nullable(Name),
    dirtyHash: digest,
    manifestHash: ContentDigest,
    excludes: names,
    skippedFiles: Type.Optional(Type.Array(Obj({ path: Name, reason: Name }))),
  }),
  Feature: entity("fea", {
    projectId: id("prj"),
    stableKey: Name,
    requirementRefs: Type.Array(id("req")),
    routeRefs: names,
    endpointRefs: names,
  }),
  Requirement: entity("req", {
    text: Description,
    acceptanceCriteria: Type.Array(Description),
    sourceRefs: refs,
    originKind: Enum(["explicit", "user_spec", "inferred", "observed"]),
    confidence: nullable(Type.Number({ minimum: 0, maximum: 1 })),
    approval: nullable(id("apr")),
  }),
  DiscoveryJob: entity("dsc", {
    inputsFingerprint: ContentDigest,
    phase: Enum([
      "queued",
      "extracting",
      "normalizing",
      "exploring",
      "planning",
      "validating",
      "completed",
      "cancelled",
      "failed",
    ]),
    perFeatureResults: Type.Array(
      Obj({
        featureId: id("fea"),
        status: Enum(["ready", "partial", "unreachable", "needs_input"]),
        evidenceRefs: refs,
        errors: names,
      }),
    ),
    limits: ExecutionLimits,
    usage: Json,
  }),
  ProposalBatch: entity("pbt", {
    projectId: id("prj"),
    sourceSnapshotId: Name,
    version: Version,
    state: Enum(["proposed", "accepted", "rejected", "stale"]),
  }),
  Proposal: entity("pro", {
    batchId: id("pbt"),
    plan: Type.Union([ExecutablePlan, IntentPlan]),
    requirementRefs: Type.Array(id("req")),
    evidenceRefs: refs,
    warnings: names,
    state: Enum(["proposed", "accepted", "rejected"]),
    validation: Type.Optional(Enum(["valid", "invalid", "needs_input"])),
  }),
  TestCase: entity("tst", {
    projectId: id("prj"),
    name: Name,
    activeRevisionId: nullable(id("rev")),
    tags: names,
    priority: Priority,
    archivedAt: nullable(Timestamp),
  }),
  TestRevision: entity("rev", {
    testId: id("tst"),
    ordinal: Version,
    contentHash: ContentDigest,
    plan: nullable(ExecutablePlan),
    codeArtifactId: nullable(id("art")),
    codeRef: Type.Optional(CodeReference),
    runnerKind: Enum(["playwright", "http", "python"]),
    author: Name,
    parentId: nullable(id("rev")),
    origin: Enum(["manual", "generated", "healed", "imported"]),
  }),
  Suite: entity("sui", {
    workspaceId: id("ws"),
    name: Name,
    version: Version,
    members: Type.Array(id("tst")),
    environmentBindings: Type.Record(Type.String(), id("env")),
  }),
  BatchRun: entity("bat", {
    selectionSnapshot: Json,
    requestedCount: Nonnegative,
    memberRuns: Type.Array(id("run")),
    rejectedMembers: Type.Array(Obj({ memberKey: Name, reasonCode: Enum(reasonCodes) })),
    commit: nullable(Name),
    aggregate: Obj({ counts: BatchCounts, gate: Gate }),
  }),
  Run: entity("run", {
    testId: id("tst"),
    revisionId: id("rev"),
    environmentRevisionId: id("evr"),
    batchId: nullable(id("bat")),
    matrixCell: Json,
    mode: Mode,
    phase: Phase,
    status: RunResult.properties.status,
    outcome: nullable(Outcome),
    origin: Name,
    gatePolicy: Json,
    gate: Gate,
    cleanupOutcome: CleanupOutcome,
    analysisStatus: AnalysisStatus,
  }),
  Attempt: entity("att", {
    runId: id("run"),
    number: Version,
    workerId: nullable(id("wrk")),
    seed: Type.Integer(),
    phase: Phase,
    startedAt: nullable(Timestamp),
    endedAt: nullable(Timestamp),
    outcome: nullable(Outcome),
  }),
  StepResult,
  VariableValue: entity("var", {
    batchId: nullable(id("bat")),
    producerRunId: id("run"),
    producerStepId: Name,
    name: Name,
    type: Enum(["string", "number", "boolean", "object", "array", "null"]),
    encryptedValueRef: nullable(Name),
    taint: Enum(["public", "sensitive"]),
  }),
  ResourceRecord: entity("res", {
    creatorAttemptId: id("att"),
    resourceType: Name,
    handleRef: nullable(Name),
    cleanupPlan: Json,
    state: Enum(["planned", "created", "cleanup_pending", "cleaned", "orphaned", "uncertain"]),
    ownerProof: nullable(EvidenceRef),
  }),
  Artifact: entity("art", {
    runId: nullable(id("run")),
    attemptId: nullable(id("att")),
    revisionId: id("rev"),
    snapshotId: nullable(id("snp")),
    kind: Name,
    hash: digest,
    bytes: Nonnegative,
    mime: Name,
    storageKey: Name,
    state: ArtifactState,
    redactionStatus: RedactionStatus,
  }),
  Snapshot: entity("snp", {
    runId: id("run"),
    attemptId: id("att"),
    revisionId: id("rev"),
    manifestHash: ContentDigest,
    committedAt: Timestamp,
    redactionPolicyHash: ContentDigest,
    executionSnapshot: Type.Optional(Json),
  }),
  Analysis: entity("ana", {
    runId: id("run"),
    snapshotId: id("snp"),
    facts: Type.Array(Obj({ text: Description, evidenceRefs: refs })),
    hypotheses: Type.Array(
      Obj({
        text: Description,
        supports: refs,
        contradicts: refs,
        confidence: Type.Number({ minimum: 0, maximum: 1 }),
        calibrated: Type.Boolean(),
      }),
    ),
    failureKind: Enum([
      "product_bug",
      "test_fragility",
      "environment",
      "contract_violation",
      "security_policy",
      "unknown",
    ]),
    confidence: nullable(Type.Number({ minimum: 0, maximum: 1 })),
    modelCallId: nullable(id("mdl")),
    limitations: names,
    recommendedAction: Type.Optional(Description),
    fixTarget: Type.Optional(EvidenceRef),
  }),
  HealingProposal: entity("hea", {
    failedRunId: id("run"),
    baseRevisionId: id("rev"),
    candidateRevisionId: id("rev"),
    diff: Description,
    preservedAssertionsHash: ContentDigest,
    status: Enum(["proposed", "approved", "rejected", "verified"]),
  }),
  Schedule: entity("sch", {
    targetId: Name,
    cron: Name,
    timezone: Name,
    nextFireAt: nullable(Timestamp),
    overlapPolicy: Enum(["forbid", "allow", "replace"]),
    budget: Json,
    state: Enum(["active", "paused", "archived"]),
  }),
  ScheduledFire: Obj({
    scheduleId: id("sch"),
    scheduledAt: Timestamp,
    eventId: id("evt"),
    state: Enum(["dispatched", "skipped", "misfire", "overlap"]),
    batchId: nullable(id("bat")),
    reasonCode: Type.Optional(Enum(reasonCodes)),
  }),
  ModelCall: entity("mdl", {
    purpose: Enum(["normalize", "plan", "resolve_action", "generate_code", "analyze", "heal"]),
    provider: Name,
    model: Name,
    promptHash: ContentDigest,
    inputRefs: refs,
    tokens: nullable(Nonnegative),
    cost: nullable(Type.Number({ minimum: 0 })),
    latency: Nonnegative,
    outcome: Enum(["success", "invalid", "failed", "cancelled"]),
  }),
  AuditEvent: entity("aud", {
    actor: Name,
    action: Name,
    resourceId: Name,
    requestId: Name,
    beforeHash: digest,
    afterHash: digest,
    timestamp: Timestamp,
  }),
  IdempotencyReceipt: entity("idr", {
    tenant: id("ws"),
    actorScope: Name,
    operation: Name,
    key: Type.String({ minLength: 16, maxLength: 128 }),
    requestHash: ContentDigest,
    responseRef: Name,
    expiresAt: Timestamp,
  }),
  JobLease: entity("job", {
    queue: Name,
    resourceId: Name,
    leaseExpiresAt: nullable(Timestamp),
    fence: Nonnegative,
    attempts: Nonnegative,
    availableAt: Timestamp,
  }),
  OutboxEvent: entity("evt", {
    aggregateId: Name,
    seq: Nonnegative,
    type: Name,
    payloadRef: Name,
    deliveryState: Enum(["pending", "delivered", "dead_letter"]),
  }),
  Approval: entity("apr", {
    actorId: Name,
    reviewerId: Name,
    actionSet: names,
    revisionHash: ContentDigest,
    environmentRevisionId: id("evr"),
    originSet: names,
    expiresAt: Timestamp,
    revokedAt: nullable(Timestamp),
    policyHash: ContentDigest,
  }),
  AuthProfile: entity("aup", {
    projectId: id("prj"),
    version: Version,
    kind: Enum(["form", "basic", "bearer", "api-key", "cookie", "oauth", "oidc", "manual"]),
    originBindings: names,
    secretRefs: Type.Array(id("sec")),
    refreshPolicy: Json,
  }),
  AuthCheckpoint: entity("acp", {
    runId: id("run"),
    attemptId: id("att"),
    authProfileId: id("aup"),
    challengeRef: Name,
    expiresAt: Timestamp,
    state: Enum(["pending", "completed", "cancelled", "expired"]),
  }),
  Worker: entity("wrk", {
    identityRef: Name,
    capabilities: names,
    imageDigests: names,
    labels: Type.Record(Type.String(), Name),
    state: Enum(["enrolling", "ready", "draining", "revoked", "offline"]),
    lastHeartbeatAt: nullable(Timestamp),
  }),
  Delivery: entity("dlv", {
    eventId: id("evt"),
    destinationRef: Name,
    payloadHash: ContentDigest,
    attempts: Nonnegative,
    nextAttemptAt: nullable(Timestamp),
    state: Enum(["pending", "delivered", "dead_letter"]),
  }),
  DeletionOperation: entity("del", {
    resourceRefs: names,
    requestedBy: Name,
    revokedAt: Timestamp,
    physicalState: Enum(["pending", "running", "completed", "failed"]),
    backupHolds: names,
    errors: names,
  }),
  MemoryEntry: entity("mry", {
    projectId: id("prj"),
    text: Description,
    sourceRefs: refs,
    validFrom: Timestamp,
    expiresAt: nullable(Timestamp),
    approval: nullable(id("apr")),
    version: Version,
    tombstoneAt: nullable(Timestamp),
  }),
  VisualBaseline: entity("vbl", {
    revisionId: id("rev"),
    matrixDigest: ContentDigest,
    artifactId: id("art"),
    maskPolicyHash: ContentDigest,
    thresholdVersion: Name,
    approval: nullable(id("apr")),
  }),
  Evaluation: entity("evl", {
    corpusDigest: ContentDigest,
    cohort: Name,
    trialRefs: names,
    oracleVersion: Name,
    metrics: Type.Record(Type.String(), Type.Number()),
    decision: Name,
    limitations: names,
  }),
  PermissionGrant,
  ArtifactManifest,
};
export const FeatureMap = Obj({
  projectId: id("prj"),
  version: Version,
  features: Type.Array(entities.Feature),
  sourceRevisionIds: Type.Array(id("svr")),
  status: Enum(["ready", "partial", "needs_input"]),
});
export const DiscoveryRequest = Obj({
  projectId: id("prj"),
  sourceRevisionIds: Type.Array(id("svr")),
  scope: names,
  budget: Json,
  inputsFingerprint: Type.Optional(ContentDigest),
});
export const DiscoveryResult = entities.DiscoveryJob;
export const ExecutionSnapshot = Obj({
  schemaVersion: Type.Literal("1.0.0"),
  runId: id("run"),
  revisionId: id("rev"),
  environmentRevisionId: id("evr"),
  mode: Mode,
  healingPolicy: Enum(["off", "propose", "apply"]),
  seed: Type.Integer(),
  target: Obj({
    baseUrl: Type.String({ format: "uri" }),
    networkProfile: Enum(["public", "local-loopback", "private"]),
  }),
  provenance: Obj({ commitSha: nullable(Name), dirtyHash: digest, deploymentId: nullable(Name) }),
  limits: ExecutionLimits,
  secretRefs: Type.Array(Obj({ id: id("sec"), version: Version, hash: ContentDigest })),
  requiredArtifacts: names,
  imageDigest: Type.Optional(Name),
  browserVersion: Type.Optional(Name),
  dependenciesLockHash: Type.Optional(ContentDigest),
  capabilityManifestHash: Type.Optional(ContentDigest),
  policyHash: Type.Optional(ContentDigest),
  sourceRevisionIds: Type.Optional(Type.Array(id("svr"))),
  modelConfigHash: Type.Optional(ContentDigest),
  buildInputsHash: Type.Optional(ContentDigest),
  seccompHash: Type.Optional(ContentDigest),
  reproductionLimitations: Type.Optional(names),
  sealedAt: Type.Optional(Timestamp),
});
export const IntegrationEvent = Obj({
  eventId: Name,
  provider: Name,
  payloadHash: ContentDigest,
  occurredAt: Timestamp,
  receiptRef: Name,
});
export const CohortManifest = Obj({
  corpusDigest: ContentDigest,
  cohort: Name,
  trialRefs: names,
  oracleVersion: Name,
  denominator: Nonnegative,
});
export const EvaluationResult = entities.Evaluation;
export const TraceabilityRecord = Obj({
  id: Name,
  milestone: Enum(["M0", "M1", "M2", "M3", "M4", "M5", "M6"]),
  ownerRole: Name,
  status: Enum(["planned", "implemented", "verified", "blocked"]),
  scenario: names,
  oracle: names,
  evidence: names,
});
export const ModelRequest = Obj({
  purpose: Name,
  provider: Name,
  model: Name,
  promptVersion: Name,
  schemaVersion: Name,
  inputRefs: refs,
  responseSchema: Name,
  reasoningEffort: Type.Optional(Enum(["low", "medium", "high"])),
  policyHash: ContentDigest,
});
export const ModelResponse = Obj({
  modelCallId: id("mdl"),
  output: Json,
  usage: nullable(Json),
  warnings: names,
});
