import { jsonSchema } from "@testmaster/contracts";
import { columnName, tableCatalog } from "./schema.js";

export const contractProjections = {
  ...Object.fromEntries(
    Object.entries(tableCatalog).map(([kind, value]) => [
      kind,
      {
        table: value.table,
        fields: Object.fromEntries(value.fields.map((field) => [field, columnName(field)])),
      },
    ]),
  ),
  ModelCall: {
    table: "model_calls",
    fields: {
      purpose: "purpose",
      provider: "provider",
      model: "model",
      promptHash: "prompt_hash",
      latency: "latency",
      outcome: "outcome",
    },
  },
  IdempotencyReceipt: {
    table: "idempotency_receipts",
    fields: {
      actorScope: "actor_scope",
      operation: "operation",
      key: "key",
      requestHash: "request_hash",
      expiresAt: "expires_at",
    },
  },
  JobLease: {
    table: "job_leases",
    fields: {
      queue: "queue",
      resourceId: "resource_id",
      leaseExpiresAt: "lease_expires_at",
      fence: "fence",
      attempts: "attempts",
      availableAt: "available_at",
    },
  },
  OutboxEvent: {
    table: "outbox",
    fields: {
      aggregateId: "aggregate_id",
      seq: "seq",
      type: "type",
      payloadRef: "payload_ref",
      deliveryState: "delivery_state",
    },
  },
} satisfies Record<string, { table: string; fields: Record<string, string> }>;
export interface ScalarRule {
  kind: string;
  table: string;
  field: string;
  column: string;
  schema: Record<string, unknown>;
}
export function projectionRules(): ScalarRule[] {
  const result: ScalarRule[] = [];
  for (const [kind, projection] of Object.entries(contractProjections)) {
    const schema = jsonSchema(kind);
    const variants = (schema.anyOf as Record<string, unknown>[] | undefined) ?? [schema];
    const properties: Record<string, Record<string, unknown>> = {};
    for (const variant of variants)
      for (const [key, value] of Object.entries(
        (variant.properties ?? {}) as Record<string, Record<string, unknown>>,
      )) {
        if (properties[key] && JSON.stringify(properties[key]) !== JSON.stringify(value))
          properties[key] = { anyOf: [properties[key], value] };
        else properties[key] = value;
      }
    for (const [field, column] of Object.entries(projection.fields)) {
      const source = properties[field];
      if (source) result.push({ kind, table: projection.table, field, column, schema: source });
    }
    result.push({
      kind,
      table: projection.table,
      field: "version",
      column: "version",
      schema: { type: "integer", minimum: 1 },
    });
  }
  return result;
}
export function scalarPredicate(schema: Record<string, unknown>, expression: string): string {
  if (Array.isArray(schema.anyOf))
    return `(${schema.anyOf.map((child) => scalarPredicate(child, expression)).join(" OR ")})`;
  if (schema.type === "null") return `${expression} IS NULL`;
  if (Object.hasOwn(schema, "const"))
    return `${expression} = '${String(schema.const).replaceAll("'", "''")}'`;
  const rules: string[] = [];
  if (schema.type === "boolean") rules.push(`${expression} IN (0,1)`);
  if (schema.minimum !== undefined) rules.push(`${expression} >= ${Number(schema.minimum)}`);
  if (schema.maximum !== undefined) rules.push(`${expression} <= ${Number(schema.maximum)}`);
  if (schema.minLength !== undefined)
    rules.push(`length(${expression}) >= ${Number(schema.minLength)}`);
  if (schema.maxLength !== undefined)
    rules.push(`length(${expression}) <= ${Number(schema.maxLength)}`);
  return rules.length ? `(${rules.join(" AND ")})` : "1=1";
}
/** Tables introduced after 0004 receive their generated constraints in their own forward migration. */
export const constraintMigrations = {
  "0004_contract_constraints": null,
  "0007_m3_contract_constraints": ["analyses", "healing_proposals", "deliveries"],
} as const satisfies Record<string, readonly string[] | null>;
export type ConstraintMigration = keyof typeof constraintMigrations;
export function generatedConstraintMigrations(
  migration: ConstraintMigration = "0004_contract_constraints",
): Record<"sqlite" | "postgres", string> {
  const later = new Set<string>(
    Object.values(constraintMigrations).flatMap((tables) => (tables ? [...tables] : [])),
  );
  const selected = constraintMigrations[migration];
  const rules = projectionRules().filter(
    (rule) =>
      scalarPredicate(rule.schema, rule.column) !== "1=1" &&
      (selected
        ? (selected as readonly string[]).includes(rule.table)
        : !later.has(rule.table)),
  );
  const grouped = new Map<string, ScalarRule[]>();
  for (const rule of rules) {
    const items = grouped.get(rule.table) ?? [];
    items.push(rule);
    grouped.set(rule.table, items);
  }
  let sqlite = "-- Generated by src/generate-contract-constraints.ts; do not edit.\n";
  let postgres = sqlite;
  for (const [table, items] of grouped) {
    const predicate = (prefix: string) =>
      items
        .map(
          (rule) =>
            `(${prefix}${rule.column} IS NULL OR ${scalarPredicate(rule.schema, `${prefix}${rule.column}`)})`,
        )
        .join(" AND ");
    sqlite += `CREATE TEMP TABLE contract_check_${table}(valid INTEGER);\nCREATE TEMP TRIGGER validate_${table} BEFORE INSERT ON contract_check_${table} WHEN NEW.valid<>1 BEGIN SELECT RAISE(ABORT,'contract constraint migration: invalid existing ${table}'); END;\nINSERT INTO contract_check_${table} SELECT CASE WHEN ${predicate("")} THEN 1 ELSE 0 END FROM ${table};\nDROP TABLE contract_check_${table};\n`;
    for (const operation of ["INSERT", "UPDATE"])
      sqlite += `CREATE TRIGGER contract_${table}_${operation.toLowerCase()} BEFORE ${operation} ON ${table} WHEN NOT (${predicate("NEW.")}) BEGIN SELECT RAISE(ABORT,'contract constraint violation: ${table}'); END;\n`;
    postgres += `ALTER TABLE ${table} ADD CONSTRAINT contract_${table}_projection CHECK (${predicate("").replaceAll("1=1", "TRUE")});\n`;
  }
  return { sqlite, postgres };
}
